name: Initial Action Workflow

on:
  push:

jobs:
  gitHubInfos:
    name: Get GitHub infos
    runs-on: ubuntu-latest

    steps:
      - name: "Display GitHub Context"
        id: ghdetails
        run: |
          echo "=== GitHub Context ==="
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
